WebAppMvcDupla/WebAppMvcDupla/Models/Automovel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebAppMvcDupla.Models
{
    public class Automovel : BaseModel
    {
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Cilindradas { get; set; }
        [Display(Name = "Quantidade de Rodas" )]
        public int QtRodas { get; set; }
    }
}

WebAppMvcDupla/WebAppMvcDupla/Models/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMvcDupla.Models
{
    public class BaseModel
    {
        public int Id { get; set; }
    }
}

WebAppMvcDupla/WebAppMvcDupla/Models/Caminhao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMvcDupla.Models
{
    public class Caminhao : Automovel
    {
    }
}

WebAppMvcDupla/WebAppMvcDupla/Models/Carro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMvcDupla.Models
{
    public class Carro : Automovel
    {
    }
}

WebAppMvcDupla/WebAppMvcDupla/Models/Moto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMvcDupla.Models
{
    public class Moto : Automovel
    {
    }
}

WebAppMvcDupla/WebAppMvcDupla/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMvcDupla.Models;
using WebAppMvcDupla.Repository;

namespace WebAppMvcDupla.Controllers
{
    public abstract class BaseController<M, R> : Controller where M : BaseModel where R : BaseRepository<M>
    {
        R repository;
        public BaseController(R repo)
        {
            this.repository = repo;
        }
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(M model)
        {
            repository.Create(model);
            return RedirectToAction("Create");
        }
        public ActionResult List()
        {
            return View(repository.Read());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(repository.Read(id));
        }
        [HttpPost]
        public ActionResult Edit(M model)
        {
            repository.Update(model);
            return RedirectToAction("List");
        }
        public ActionResult Delete(int id)
        {
            repository.Delete(id);
            return RedirectToAction("List");
        }
        public ActionResult Details(int id)
        {
            return View(repository.Read(id));
        }
    }
}

WebAppMvcDupla/WebAppMvcDupla/Controllers/CaminhaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMvcDupla.Models;
using WebAppMvcDupla.Repository;

namespace WebAppMvcDupla.Controllers
{
    public class CaminhaoController : BaseController<Caminhao,CaminhaoRepository>
    {
        public CaminhaoController() : base(new CaminhaoRepository())
        {
        }
    }
}

WebAppMvcDupla/WebAppMvcDupla/Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMvcDupla.Models;
using WebAppMvcDupla.Repository;

namespace WebAppMvcDupla.Controllers
{
    public class CarroController : BaseController<Carro,CarroRepository>
    {
        public CarroController() : base(new CarroRepository())
        {
        }
        
    }
}

WebAppMvcDupla/WebAppMvcDupla/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppMvcDupla.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebAppMvcDupla/WebAppMvcDupla/Controllers/MotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMvcDupla.Models;
using WebAppMvcDupla.Repository;

namespace WebAppMvcDupla.Controllers
{
    public class MotoController : BaseController<Moto,MotoRepository>
    {
        public MotoController() : base(new MotoRepository())
        {
        }
    }
}

WebAppMvcDupla/WebAppMvcDupla/Views/Caminhao/Create.cshtml
@model WebAppMvcDupla.Models.Caminhao

@{
    ViewBag.Title = "Cadastro - Caminhão";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Caminhão</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cilindradas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cilindradas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cilindradas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtRodas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QtRodas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QtRodas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar para a Lista", "List")
</div>

WebAppMvcDupla/WebAppMvcDupla/Views/Caminhao/Details.cshtml
@model WebAppMvcDupla.Models.Caminhao

@{
    ViewBag.Title = "Detalhes - Caminhão";
}

<h2>Details</h2>

<div>
    <h4>Caminhao</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cilindradas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cilindradas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtRodas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtRodas)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar para a Lista", "List")
</p>

WebAppMvcDupla/WebAppMvcDupla/Views/Caminhao/Edit.cshtml
@model WebAppMvcDupla.Models.Caminhao

@{
    ViewBag.Title = "Editar - Caminhão";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Caminhão</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cilindradas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cilindradas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cilindradas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtRodas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QtRodas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QtRodas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar para a Lista", "List")
</div>

WebAppMvcDupla/WebAppMvcDupla/Views/Caminhao/Index.cshtml
@{
    ViewBag.Title = "Menu - Caminhão";
}

<h2>MÓDULO CAMINHÃO</h2>
@Html.ActionLink("Cadastrar", "Create")
@Html.ActionLink("Lista", "List")

WebAppMvcDupla/WebAppMvcDupla/Views/Caminhao/List.cshtml
@model IEnumerable<WebAppMvcDupla.Models.Caminhao>

@{
    ViewBag.Title = "Lista - Caminhão";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Criar Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cilindradas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QtRodas)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Marca)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Modelo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Cilindradas)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.QtRodas)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
        @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>

WebAppMvcDupla/WebAppMvcDupla/Views/Carro/Create.cshtml
@model WebAppMvcDupla.Models.Carro

@{
    ViewBag.Title = "Cadastro - Carro";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Carro</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cilindradas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cilindradas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cilindradas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtRodas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QtRodas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QtRodas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar para a Lista", "List")
</div>

WebAppMvcDupla/WebAppMvcDupla/Views/Carro/Details.cshtml
@model WebAppMvcDupla.Models.Carro

@{
    ViewBag.Title = "Detalhes - Carro";
}

<h2>Details</h2>

<div>
    <h4>Carro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cilindradas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cilindradas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtRodas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtRodas)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar para a Lista", "List")
</p>

WebAppMvcDupla/WebAppMvcDupla/Views/Carro/Edit.cshtml
@model WebAppMvcDupla.Models.Carro

@{
    ViewBag.Title = "Editar - Carro";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Carro</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cilindradas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cilindradas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cilindradas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtRodas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QtRodas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QtRodas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar para a Lista", "List")
</div>

WebAppMvcDupla/WebAppMvcDupla/Views/Carro/Index.cshtml
@{
    ViewBag.Title = "Menu - Carro";
}

<h2>MÓDULO CARRO</h2>
@Html.ActionLink("Cadastrar", "Create")
@Html.ActionLink("Lista", "List")

WebAppMvcDupla/WebAppMvcDupla/Views/Carro/List.cshtml
@model IEnumerable<WebAppMvcDupla.Models.Carro>

@{
    ViewBag.Title = "Lista - Carro";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Criar Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cilindradas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QtRodas)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Marca)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Modelo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Cilindradas)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.QtRodas)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
        @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>

WebAppMvcDupla/WebAppMvcDupla/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Menu";
}

<div id="home">
    <h1>Seja bem-vindo</h1>
</div>

WebAppMvcDupla/WebAppMvcDupla/Views/Moto/Create.cshtml
@model WebAppMvcDupla.Models.Moto

@{
    ViewBag.Title = "Cadastro - Moto";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Moto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cilindradas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cilindradas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cilindradas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtRodas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QtRodas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QtRodas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar para a Lista", "List")
</div>

WebAppMvcDupla/WebAppMvcDupla/Views/Moto/Details.cshtml
@model WebAppMvcDupla.Models.Moto

@{
    ViewBag.Title = "Detalhes - Moto";
}

<h2>Details</h2>

<div>
    <h4>Moto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cilindradas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cilindradas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtRodas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtRodas)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar para a Lista", "List")
</p>

WebAppMvcDupla/WebAppMvcDupla/Views/Moto/Index.cshtml
@{
    ViewBag.Title = "Menu - Moto";
}

<h2>MÓDULO MOTO</h2>
@Html.ActionLink("Cadastrar", "Create")
@Html.ActionLink("Lista", "List")

WebAppMvcDupla/WebAppMvcDupla/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Automóveis", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Gestão de Carros", "Index", "Carro")</li>
                    <li>@Html.ActionLink("Gestão de Caminhãos", "Index", "Caminhao")</li>
                    <li>@Html.ActionLink("Gestão de Motos", "Index", "Moto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>